#!/usr/bin/env bash

#check for bucket name
if [ -z "$1" ]; then
  echo "There is needs to be a bucket name."
  exit 1
fi

BUCKET_NAME=$1

#https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api create-bucket \
--bucket $BUCKET_NAME \
--create-bucket-configuration="LocationConstraint=eu-north-1" \
--query Location \
--output text