#!/usr/bin/env bash

#exit immediatly if any command return error
set -e

#check for bucket name
if [ -z "$1" ]; then
  echo "There is needs to be a bucket name."
  exit 1
fi

#check for file name and prefix
if [ -z "$2" ]; then
  echo "There is needs to be a file name and prefix."
  exit 1
fi

BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename $FILENAME)

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY