#!/usr/bin/env bash

#exit immediatly if any command return error
set -e

#check for bucket name
if [ -z "$1" ]; then
  echo "There is needs to be a bucket name."
  exit 1
fi

#check for file name and prefix
if [ -z "$2" ]; then
  echo "There is needs to be a file name and prefix."
  exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

OUTPUT_DIR="/tmp/s3-bash-scripts"

#remove folder if exists
rm -rf $OUTPUT_DIR

#output folder
mkdir -p $OUTPUT_DIR

NUM_FILES=$((RANDOM%6+5))

for((i=1; i<=$NUM_FILES; i++)); do
    
    FILE_NAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

    dd if=/dev/urandom of="$FILE_NAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null

    done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files